version: '3'
services:
    web:
        build:
            context: .
            args:
                - buildnumber=${build}
        ports:
            - "80:80"
    storage:
        image: "couchdb"