version: '3'
services:
    web:
        build:
            context: .
            args:
                - buildnumber=${build}
        image: renkman/renkbench
        ports:
            - "80:8080"
        links:
            - storage
        depends_on: 
            - storage
        environment:
            DB_URL: http://storage:5984/
    storage:
        image: couchdb