version: '3'
services:
    web:
        build:
            context: .
            args:
                - BUILDNUMBER=${BUILDNUMBER}
        image: renkman/renkbench
        ports:
            - "80:8080"
        links:
            - storage
        depends_on: 
            - storage
        environment:
            - DB_URL: http://storage:5984/
            - RELEASENUMBER=${RELEASENUMBER}
    storage:
        image: couchdb